export const courseNavUrl = {
    logoUrl : 'runestone.academy/',
    courseHomeUrl : '/ns/course/index',
    assignmentsUrl : '/assignment/student/chooseAssignment',
    practiceUrl : /\/assignments\/practice/,
    studentPeerInstructionUrl : '/runestone/peer/student.html',
    progressPageUrl : '/runestone/dashboard/studentreport',
    changeCourseUrl : '/runestone/default/courses',
    editProfileUrl : '/runestone/default/user/profile',
    changePasswordUrl : '/runestone/default/user/change_password',
    backToTextbookUrl : '/ns/books/published/otheruniversity_ac-single_fall24/frontmatter.html',
    createCourseUrl : '/runestone/designer/index',
    runestoneNewsUrl : 'https://blog.runestone.academy/',
    instructorsPageUrl : /\/runestone\/admin/,
    instructorPeerInstructionUrl : '/runestone/peer/instructor.html',
    authorToolsUrl : 'https://author.runestone.academy/author',
    editorialPageUrl : '/runestone/admin/manage_exercises',
    requestInvoiceUrl : '/assignment/instructor/invoice_request',
    faqUrl : 'https://blog.runestone.academy/pages/faq.html',
    instructorsGuideUrl : 'https://guide.runestone.academy/',
    aboutRunestoneUrl : 'https://blog.runestone.academy/pages/about.html',
    reportAProblemUrl : '/runestone/default/reportabug',
}